# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'informatic_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(323, 142)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_mail_phone = QtWidgets.QLabel(self.centralwidget)
        self.label_mail_phone.setObjectName("label_mail_phone")
        self.horizontalLayout.addWidget(self.label_mail_phone)
        self.lineEdit_mail = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mail.setObjectName("lineEdit_mail")
        self.horizontalLayout.addWidget(self.lineEdit_mail)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_2.addWidget(self.lineEdit_password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_reg = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reg.setObjectName("pushButton_reg")
        self.horizontalLayout_3.addWidget(self.pushButton_reg)
        self.pushButton_entry = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_entry.setObjectName("pushButton_entry")
        self.horizontalLayout_3.addWidget(self.pushButton_entry)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 323, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_mail_phone.setText(_translate("MainWindow", "e-mail/phone"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.pushButton_reg.setText(_translate("MainWindow", "Registration"))
        self.pushButton_entry.setText(_translate("MainWindow", "Entry"))
